# Generated by Django 2.2.2 on 2022-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expired',
            field=models.CharField(default='Hello', max_length=100),
        ),
    ]
